use_frameworks!

platform :ios, '10.0'

target 'ImageCoreEngineMagic_Example' do
  pod 'ImageCoreEngineMagic', :path => '../'

  target 'ImageCoreEngineMagic_Tests' do
    inherit! :search_paths

    
  end
end
